---
- name: Copies a file from one host to another
  hosts: targetServer
  tasks:

    - name: Transfer file from sourceServer to targetServer
      ansible.posix.synchronize:
        src: "{{ srcFilePath }}"
        dest: "{{ targetFilePath }}"
      delegate_to: sourceServer

    - name: Set the permissions of the freshly copied file
      when: targetModePermissions is defined or targetOwner is defined or targetGroup is defined
      ansible.builtin.file:
        mode: "{{ targetModePermissions | default(omit) }}"
        owner: "{{ targetOwner | default(omit) }}"
        group: "{{ targetGroup | default(omit) }}"
        path: "{{ targetFilePath }}"
      delegate_to: targetServer
