---
- name: Copies a file from one host to another
  hosts: targetServer
  tasks:

    - name: SCP things around because the syncronize module sucks
      ansible.builtin.shell:
        cmd: "scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o LogLevel=ERROR {{ hostvars['sourceServer'].ansible_host }}:{{ srcFilePath }} {{ targetFilePath }}"

    # https://stackoverflow.com/questions/25505146/how-can-i-copy-files-between-two-managed-nodes-using-ansible
    # - name: Transfer file from sourceServer to targetServer
    #   ansible.posix.synchronize:
    #     src: "{{ srcFilePath }}"
    #     dest: "{{ targetFilePath }}"
    #     compress: "{{ compressTransfer | default(false) }}"
    #   delegate_to: sourceServer

    - name: Set the permissions of the freshly copied file
      when: targetModePermissions is defined or targetOwner is defined or targetGroup is defined
      ansible.builtin.file:
        mode: "{{ targetModePermissions | default(omit) }}"
        owner: "{{ targetOwner | default(omit) }}"
        group: "{{ targetGroup | default(omit) }}"
        path: "{{ targetFilePath }}"
      #delegate_to: targetServer
