---
- name: Sets up multiple OpenShift Installer binary versions
  hosts: all

  vars:
    openshift_binary_path: /opt/bin/openshift-install
    openshift_binary_versions:
      - stable-4.18
      - stable-4.19
    openshift_binary_filename: openshift-install-rhel9-amd64.tar.gz
    openshift_binary_remote_url: https://mirror.openshift.com/pub/openshift-v4/clients/ocp

  tasks:
    - name: Ensure the OpenShift binary directory exists
      ansible.builtin.file:
        state: directory
        path: "{{ openshift_binary_path }}"
        mode: '0755'

    - name: Detect or download OpenShift Installer binaries
      ansible.builtin.include_tasks:
        file: tasks/download-binary.yaml
      loop: "{{ openshift_binary_versions }}"
      loop_control:
        loop_var: ocp_version

