---
- name: Create a post-image shutdown script
  ansible.builtin.template:
    src: post-image-shutdown.sh.j2
    dest: "{{ appliance_asset_path }}/post.sh"
    mode: '0755'

- name: Build Appliance image
  ansible.builtin.shell:
    creates: "{{ appliance_asset_path }}/appliance.raw"
    cmd: >
      podman run --rm -it --privileged
      --name appliance-builder
      --net=host{{ ' -v ' + appliance_asset_path + '/podman-wrapper:/root/.local/bin/podman' if disconnected_mirrors is defined else '' }}
      -v /etc/pki:/etc/pki:ro{{ ' -v ' + appliance_asset_path + '/registries.conf:/etc/containers/registries.conf:ro' if disconnected_mirrors is defined else '' }}
      -v {{ appliance_graph_path }}:/var/lib/containers:Z
      -v {{ appliance_asset_path }}:/assets:Z
      {{ appliance_image }} build --log-level debug
