---
- name: Create a post-image shutdown script
  ansible.builtin.template:
    src: post-image-shutdown.sh.j2
    dest: "{{ appliance_asset_path }}/post.sh"
  mode: '0755'

- name: Build Appliance image
  ansible.builtin.shell:
    cmd: >
      podman run --rm -it --privileged
      --net=host
      -v /etc/pki:/etc/pki:ro
      -v {{ appliance_graph_path }}:/var/lib/containers:Z
      -v {{ appliance_asset_path }}:/assets:Z
      {{ appliance_image }} build --log-level debug